apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::534173283575:role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-COKPXOA5DEZ2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::534173283575:role/service-role/codebuild-eks-cicd-service-role
      username: codebuild-eks-cicd-service-role
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-20T01:53:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "17034"
  uid: eac4ed8d-8026-4747-96bc-fa5ff611ce1d
